const kommuner = [
  "Alle",
  "Alstahaug", "Alta", "Alvdal", "Andøy", "Aremark", "Arendal", "Asker", "Askøy", "Aukra",
  "Aure", "Aurland", "Aurskog-Høland", "Austevoll", "Austrheim", "Averøy", "Balsfjord",
  "Bamble", "Bardu", "Beiarn", "Bergen", "Berlevåg", "Bindal", "Birkenes", "Bjerkreim",
  "Bodø", "Bokn", "Bremanger", "Brønnøy", "Bygland", "Bykle", "Bærum", "Bø i Nordland",
  "Bø i Telemark", "Bømlo", "Dovre", "Drammen", "Drangedal", "Dyrøy", "Dønna", "Eidskog",
  "Eidsvoll", "Eigersund", "Elverum", "Enebakk", "Engerdal", "Etne", "Etnedal", "Evenes",
  "Evje og Hornnes", "Farsund", "Fauske", "Fedje", "Fitjar", "Fjaler", "Fjord", "Flatanger",
  "Flekkefjord", "Flesberg", "Flå", "Folldal", "Forsand", "Frogn", "Frøya", "Fyresdal",
  "Færder", "Gamvik", "Gausdal", "Gildeskål", "Giske", "Gjemnes", "Gjerdrum", "Gjerstad",
  "Gjesdal", "Gjøvik", "Gloppen", "Gol", "Gran", "Grane", "Gratangen", "Grimstad", "Grong",
  "Grue", "Gulen", "Hadsel", "Halden", "Hamar", "Hamarøy", "Hareid", "Harstad", "Hasvik",
  "Hattfjelldal", "Haugesund", "Hemnes", "Hemsedal", "Herøy (Møre og Romsdal)",
  "Herøy (Nordland)", "Hitra", "Hjartdal", "Hjelmeland", "Hol", "Hole", "Holmestrand",
  "Holtålen", "Horten", "Hurdal", "Hustadvika", "Hvaler", "Hyllestad", "Hægebostad",
  "Høyanger", "Høylandet", "Inderøy", "Indre Fosen", "Iveland", "Jevnaker", "Karasjok",
  "Karlsøy", "Karmøy", "Kautokeino", "Kinn", "Klepp", "Kongsberg", "Kongsvinger", "Kragerø",
  "Kristiansand", "Kristiansund", "Krødsherad", "Kvam", "Kvinesdal", "Kvinnherad",
  "Kviteseid", "Kvitsøy", "Kvæfjord", "Kvænangen", "Kåfjord", "Lærdal", "Lødingen", "Lørenskog",
  "Løten", "Larvik", "Lavangen", "Lebesby", "Leirfjord", "Leksvik", "Leka", "Lesja", "Levanger",
  "Lier", "Lierne", "Lillehammer", "Lillesand", "Lillestrøm", "Lindesnes", "Lom", "Loppa",
  "Lund", "Lunner", "Lurøy", "Luster", "Lyngdal", "Lyngen", "Lærdal", "Malvik", "Marker",
  "Masfjorden", "Melhus", "Meløy", "Meråker", "Midtre Gauldal", "Modalen", "Modum", "Molde",
  "Moskenes", "Moss", "Målselv", "Namdalseid", "Namsskogan", "Namsos", "Nannestad", "Narvik",
  "Nes", "Nesbyen", "Nesna", "Nesset", "Nissedal", "Nittedal", "Nome", "Nord-Aurdal",
  "Nord-Fron", "Nord-Odal", "Nordkapp", "Nordre Follo", "Nordreisa", "Notodden", "Nærøysund",
  "Oppdal", "Oppegård", "Orkland", "Os", "Oslo", "Osterøy", "Overhalla", "Porsanger",
  "Porsgrunn", "Rakkestad", "Rana", "Randaberg", "Rauma", "Rendalen", "Rennebu", "Rindal",
  "Ringebu", "Ringerike", "Ringsaker", "Risør", "Rollag", "Rælingen", "Rødøy", "Røros",
  "Røst", "Røyken", "Røyrvik", "Salangen", "Saltdal", "Samnanger", "Sande", "Sandefjord",
  "Sandnes", "Sarpsborg", "Sauda", "Sel", "Selbu", "Selje", "Seljord", "Sigdal", "Siljan",
  "Sirdal", "Skaun", "Skien", "Skiptvet", "Skjåk", "Skodje", "Skånland", "Smøla", "Snillfjord",
  "Snåsa", "Sogndal", "Sokndal", "Sola", "Solund", "Sortland", "Spydeberg", "Stange",
  "Stathelle", "Stavanger", "Steigen", "Steinkjer", "Stjørdal", "Stord", "Stor-Elvdal",
  "Strand", "Stranda", "Stryn", "Sula", "Suldal", "Sund", "Sunndal", "Surnadal", "Sveio",
  "Svelvik", "Sykkylven", "Sømna", "Søndre Land", "Sør-Aurdal", "Sør-Fron", "Sør-Odal",
  "Sørreisa", "Sør-Varanger", "Tana", "Time", "Tingvoll", "Tinn", "Tjeldsund", "Tokke",
  "Tolga", "Torsken", "Tranøy", "Tromsø", "Trondheim", "Trysil", "Træna", "Tvedestrand",
  "Tydal", "Tynset", "Tysnes", "Tysvær", "Tønsberg", "Ullensaker", "Ullensvang", "Ulstein",
  "Ulvik", "Utsira", "Vadsø", "Vaksdal", "Valle", "Vang", "Vanylven", "Vardø", "Vefsn",
  "Vega", "Vegårshei", "Vennesla", "Verdal", "Verran", "Vestby", "Vestnes", "Vestre Slidre",
  "Vestre Toten", "Vestvågøy", "Vik", "Viken", "Vindafjord", "Volda", "Voss", "Vågan",
  "Vågsøy", "Vågå", "Våler", "Værøy", "Våler i Østfold", "Øksnes", "Ørland", "Ørskog", "Ørsta",
  "Østre Toten", "Øvre Eiker", "Øyer", "Øygarden", "Åfjord", "Ål", "Ålesund", "Åmli", "Åmot",
  "Årdal", "Ås", "Åseral"
];

export default kommuner;
