const kommuner = [
  "Alle",
  "Alstahaug", "Alta", "Alvdal", "Andøy", "Aremark", "Arendal", "Asker", "Askøy", "Aukra",
  "Aure", "Aurland", "Aurskog-Høland", "Austevoll", "Austrheim", "Averøy", "Balsfjord",
  "Bamble", "Bardu", "Beiarn", "Bergen", "Berlevåg", "Bindal", "Birkenes", "Bjerkreim",
  "Bjugn", "Bodø", "Bokn", "Bremanger", "Brønnøy", "Bygland", "Bykle", "Bærum", "Bø",
  "Bømlo", "Dovre", "Drammen", "Drangedal", "Dyrøy", "Dønna", "Eidskog", "Eidsvoll",
  "Eigersund", "Elverum", "Enebakk", "Engerdal", "Etne", "Etnedal", "Evenes", "Evje og Hornnes",
  "Farsund", "Fauske", "Fedje", "Fitjar", "Fjaler", "Fjord", "Flatanger", "Flå", "Flekkefjord",
  "Flesberg", "Flå", "Folkestad", "Forsand", "Fosnes", "Fredrikstad", "Frogn", "Frøya", "Fusa",
  "Fyresdal", "Færder", "Gamvik", "Gausdal", "Gildeskål", "Giske", "Gjemnes", "Gjerdrum",
  "Gjerstad", "Gjesdal", "Gjøvik", "Gloppen", "Gol", "Gran", "Grane", "Gratangen", "Grimstad",
  "Grong", "Grue", "Gulen", "Hadsel", "Halden", "Hamar", "Hamnes", "Haram", "Hareid", "Harstad",
  "Hasvik", "Hattfjelldal", "Haugesund", "Hemnes", "Hemsedal", "Herøy", "Hitra", "Hjartdal",
  "Hjelmeland", "Hol", "Hole", "Holmestrand", "Holtålen", "Horten", "Hurdal", "Hustadvika",
  "Hvaler", "Hyanger", "Hyllestad", "Hægebostad", "Høyanger", "Høylandet", "Inderøy", "Indre Fosen",
  "Iveland", "Jevnaker", "Karasjok", "Karlsøy", "Karmøy", "Kautokeino", "Kinn", "Klepp",
  "Kongsberg", "Kongsvinger", "Kragerø", "Kristiansand", "Kristiansund", "Krødsherad", "Kvam",
  "Kvinesdal", "Kvinnherad", "Kviteseid", "Kvitsøy", "Kvæfjord", "Kvænangen", "Kåfjord", "Lardal",
  "Larvik", "Lavangen", "Lebesby", "Leikanger", "Leirfjord
